
# Note that the below url has the directory "spin-lab-site"
# specified after the top level domain name.  This screws up
# resource references in posts!
# Therefore need to specify canonifyurls = true to fix this.

baseURL = 'https://spinlab-uom.github.io'
#canonifyurls = true # maybe don't need this true anymore now that we have no path after the domain

languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 12 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "images/Logos/logo.png"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "dark-gray"
  recent_posts_number = 6

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"